# Generated by Django 6.0.5 on 2026-05-22 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=120, verbose_name='ID externo')),
                ('full_name', models.CharField(max_length=240, verbose_name='nome')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefone')),
                ('city', models.CharField(blank=True, db_index=True, max_length=160, verbose_name='cidade')),
                ('state', models.CharField(default='MS', max_length=2, verbose_name='estado')),
                ('neighborhood', models.CharField(blank=True, max_length=180, verbose_name='bairro')),
                ('profile', models.CharField(blank=True, max_length=180, verbose_name='perfil')),
                ('source', models.CharField(blank=True, max_length=180, verbose_name='fonte')),
                ('consent_status', models.CharField(choices=[('pending', 'Pendente'), ('granted', 'Autorizado'), ('opted_out', 'Não receber mensagens')], default='pending', max_length=24, verbose_name='consentimento')),
                ('notes_summary', models.TextField(blank=True, verbose_name='resumo')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='dados de origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='ContactInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='WhatsApp', max_length=80, verbose_name='canal')),
                ('summary', models.TextField(verbose_name='registro')),
                ('happened_at', models.DateTimeField(verbose_name='data do contato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_interactions', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='contacts.contact', verbose_name='contato')),
            ],
            options={
                'verbose_name': 'interação',
                'verbose_name_plural': 'interações',
                'ordering': ('-happened_at',),
            },
        ),
    ]
