# Generated by Django 6.0.5 on 2026-05-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary', models.CharField(max_length=240, verbose_name='beneficiário')),
                ('city', models.CharField(blank=True, db_index=True, max_length=160, verbose_name='cidade')),
                ('year', models.PositiveSmallIntegerField(verbose_name='ano')),
                ('ministry', models.CharField(blank=True, max_length=160, verbose_name='ministério')),
                ('value_destined', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor destinado')),
                ('value_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor pago')),
                ('status', models.CharField(blank=True, max_length=180, verbose_name='situação')),
                ('object', models.TextField(blank=True, verbose_name='objeto')),
                ('source', models.CharField(blank=True, max_length=180, verbose_name='fonte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'emenda',
                'verbose_name_plural': 'emendas',
                'ordering': ('-year', 'city', 'beneficiary'),
            },
        ),
    ]
