# Generated by Django 6.0.5 on 2026-05-22 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilizationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='nome')),
                ('city', models.CharField(blank=True, db_index=True, max_length=160, verbose_name='cidade')),
                ('kind', models.CharField(max_length=120, verbose_name='tipo')),
                ('member_count', models.PositiveIntegerField(default=0, verbose_name='quantidade de membros')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='contacts.contact', verbose_name='liderança')),
            ],
            options={
                'verbose_name': 'grupo de mobilização',
                'verbose_name_plural': 'grupos de mobilização',
                'ordering': ('city', 'name'),
            },
        ),
    ]
