# Generated by Django 6.0.5 on 2026-05-22 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=180, verbose_name='nome de exibição')),
                ('role', models.CharField(choices=[('viewer', 'Leitura'), ('editor', 'Edição'), ('coordinator', 'Coordenação'), ('admin', 'Administração')], default='viewer', max_length=24, verbose_name='perfil')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil da equipe',
                'verbose_name_plural': 'perfis da equipe',
            },
        ),
    ]
