# Generated by Django 6.0.5 on 2026-05-22 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_name', models.CharField(max_length=180, verbose_name='nome do template Meta')),
                ('language_code', models.CharField(default='pt_BR', max_length=24, verbose_name='idioma')),
                ('purpose', models.CharField(max_length=180, verbose_name='objetivo')),
                ('preview_text', models.TextField(verbose_name='prévia')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'template WhatsApp',
                'verbose_name_plural': 'templates WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(blank=True, max_length=240, verbose_name='ID do provedor')),
                ('direction', models.CharField(choices=[('outbound', 'Enviada'), ('inbound', 'Recebida')], max_length=24, verbose_name='direção')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('queued', 'Na fila'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou'), ('received', 'Recebida')], default='draft', max_length=24, verbose_name='status')),
                ('body_preview', models.TextField(blank=True, verbose_name='prévia da mensagem')),
                ('provider_payload', models.JSONField(blank=True, default=dict, verbose_name='payload do provedor')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='contacts.contact', verbose_name='contato')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='enviada por')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp_integration.messagetemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'mensagem WhatsApp',
                'verbose_name_plural': 'mensagens WhatsApp',
                'ordering': ('-created_at',),
            },
        ),
    ]
